// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var plot2d;
    plot2d = function(canvas, xValues, yValues, options) {
      var ctx, displayY, i, x, yOffset, _i, _len;
      ctx = canvas.getContext("2d");
      if ((options != null ? options.modifyContext : void 0) != null) {
        options.modifyContext(ctx);
      }
      ctx.beginPath();
      yOffset = canvas.height / 2;
      i = 0;
      ctx.moveTo(xValues[i], yOffset - yValues[i]);
      for (i = _i = 0, _len = xValues.length; _i < _len; i = ++_i) {
        x = xValues[i];
        displayY = yOffset - yValues[i];
        ctx.lineTo(x, displayY);
      }
      return ctx.stroke();
    };
    return {
      plot2d: plot2d
    };
  });

}).call(this);
