// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['vendor/backbone'], function(Backbone) {
    var Point2D;
    Point2D = (function(_super) {

      __extends(Point2D, _super);

      function Point2D() {
        return Point2D.__super__.constructor.apply(this, arguments);
      }

      return Point2D;

    })(Backbone.Model);
    return {
      Point2D: Point2D
    };
  });

}).call(this);
