// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['vendor/backbone'], function(Backbone) {
    var PointSet;
    return PointSet = (function(_super) {

      __extends(PointSet, _super);

      function PointSet() {
        return PointSet.__super__.constructor.apply(this, arguments);
      }

      PointSet.prototype.xValues = function() {
        return this.get("xValues");
      };

      PointSet.prototype.yValues = function() {
        return this.get("yValues");
      };

      return PointSet;

    })(Backbone.Model);
  });

}).call(this);
